name: Production deployment

on:
  push:
    branches:
      - master
      
env:
  PACKAGES_TOKEN: ${{secrets.PACKAGES_TOKEN}}
  AZURE_RESOURCE_GROUP: cd-with-actions
  AZURE_APP_PLAN: actions-ttt-deployment
  AZURE_LOCATION: '"Central US"'
  AZURE_WEBAPP_NAME: henryjin3-ttt-app
